// 导航页配置文件
var CONFIG = {
  siteName: '我的导航',
  secretKey: 'bmFz',
  enableFireworks: true,
  hiddenGroups: ['💾 NAS & 存储'],
  groups: [
    {name:'🏠 主页',icon:'fas fa-home',items:[{name:'个人主页',icon:'fas fa-user',color:'#49b1f5',url:'https://www.yeann.cn/',desc:'个人主页'},{name:'个人博客',icon:'fas fa-blog',color:'#49b1f5',url:'https://blog.yeann.cn',desc:'Hexo 博客'},{name:'站点监控',icon:'fas fa-heartbeat',color:'#2ecc71',url:'https://status.yeann.cn/',desc:'站点监测与状态检测'}]},
    {name:'💾 NAS & 存储',icon:'fas fa-server',items:[{name:'群晖 DSM',icon:'fas fa-hard-drive',color:'#ef50a8',url:'https://qh.yeann.cn',desc:'文件管理'},{name:'File Station',icon:'fas fa-folder-open',color:'#36b37e',url:'https://file.yeann.cn/',desc:'文件浏览'},{name:'Synology Photos',icon:'fas fa-images',color:'#ff7849',url:'https://photo.yeann.cn',desc:'照片管理'},{name:'Download Station',icon:'fas fa-download',color:'#ffbf00',url:'https://qh.yeann.cn/?launchApp=SYNO.SDS.DownloadStation.Application',desc:'下载管理'},{name:'Emby',icon:'fas fa-film',color:'#7c4dff',url:'https://emby.yeann.cn/',desc:'媒体服务器'},{name:'贴吧签到',icon:'fas fa-check-circle',color:'#4878d0',url:'https://tb.960005.xyz/',desc:'自动签到'},{name:'OpenList',icon:'fas fa-list-alt',color:'#00b96b',url:'https://share.960005.xyz/',desc:'多种存储文件列表'},{name:'Portainer',icon:'fab fa-docker',color:'#0db7ed',url:'https://portainer.yeann.cn',desc:'Docker 管理'},{name:'青龙面板',icon:'fas fa-clock',color:'#2d8cf0',url:'https://ql.960005.xyz/',desc:'定时任务管理面板'},{name:'路由器',icon:'fas fa-wifi',color:'#57c850',url:'https://router.yeann.cn',desc:'网络管理'}]},
    {name:'🛠️ 工具',icon:'fas fa-wrench',items:[{name:'中科大测速',icon:'fas fa-tachometer-alt',color:'#e53935',url:'https://test.ustc.edu.cn/',desc:'测试网络上下传网速'},{name:'兰空图床',icon:'fas fa-images',color:'#00b0ff',url:'https://lsky.yeann.cn',desc:'图片托管'}]},
    {name:'🌐 外部链接',icon:'fas fa-link',items:[{name:'GitHub',icon:'fab fa-github',color:'#858585',url:'https://github.com',desc:'代码仓库'},{name:'Vercel',icon:'fas fa-bolt',color:'#000',url:'https://vercel.com',desc:'部署平台'},{name:'Cloudflare',icon:'fab fa-cloudflare',color:'#f6821f',url:'https://dash.cloudflare.com/',desc:'CDN 与安全'},{name:'阿里云 ESA',icon:'https://img.alicdn.com/tfs/TB1_ZXuNcfpK1RjSZFOXXa6nFXa-32-32.ico',color:'#ff6a00',url:'https://esa.console.aliyun.com/',desc:'边缘加速'},{name:'EdgeOne',icon:'https://cloudcache.tencent-cloud.com/qcloud/app/resource/ac/favicon.ico',color:'#0052d9',url:'https://console.cloud.tencent.com/edgeone/zones',desc:'EdgeOne 管理'}]}
  ]
};